// Centralized bilingual (FR/EN) content for the A Plus Entretien site.
// FR is the primary/default language (Montréal market); EN is the toggle.

export const content = {
  fr: {
    meta: {
      title: "A Plus Entretien | Service de nettoyage professionnel à Montréal",
    },
    nav: {
      home: "Accueil",
      about: "À propos",
      services: "Services",
      why: "Pourquoi nous",
      promotions: "Promotions",
      contact: "Contact",
      careers: "Carrières",
      cta: "Soumission gratuite",
    },
    hero: {
      eyebrow: "Entretien ménager commercial · Montréal",
      title: "Un service d'entretien ménager A+, sans compromis.",
      subtitle:
        "La propreté et la satisfaction de nos clients sont notre priorité. Une entreprise familiale montréalaise, professionnelle et assurée, au service des commerces, institutions et industries.",
      ctaPrimary: "Demander une soumission",
      ctaSecondary: "Découvrir nos services",
      badge: { title: "Équipe formée et assurée", desc: "Vérifiée, uniformée, professionnelle" },
      stats: [
        { value: "15+", label: "années d'expérience" },
        { value: "100%", label: "entreprise assurée" },
        { value: "24/7", label: "horaires flexibles" },
      ],
    },
    trustBar: [
      "Entreprise assurée",
      "Personnel formé et supervisé",
      "Produits écologiques",
      "Protocoles d'hygiène stricts",
    ],
    about: {
      eyebrow: "À propos de nous",
      title: "Une entreprise familiale, sérieuse et stable",
      paragraphs: [
        "A Plus Entretien est une entreprise montréalaise spécialisée dans le nettoyage commercial, industriel et institutionnel. Née d'une histoire familiale, notre entreprise mise sur l'intégrité, l'honnêteté et le travail bien fait.",
        "Nous traitons notre personnel comme une famille — formé, encadré et fier de son travail — parce qu'une équipe respectée offre un service constant et fiable. C'est cette culture qui nous permet de maintenir vos lieux aux plus hauts standards de propreté, jour après jour.",
      ],
      highlights: [
        { title: "Fiabilité", desc: "Un service constant sur lequel vous pouvez compter, semaine après semaine." },
        { title: "Rigueur", desc: "Des protocoles précis et un contrôle de qualité à chaque visite." },
        { title: "Confiance", desc: "Personnel vérifié, discret et respectueux de vos lieux et de vos horaires." },
      ],
    },
    services: {
      eyebrow: "Nos services",
      title: "Des solutions de nettoyage pour chaque environnement",
      subtitle:
        "Du bureau à l'usine, en passant par les cliniques et les commerces — une expertise adaptée à chaque secteur.",
      items: [
        { title: "Nettoyage commercial", desc: "Entretien régulier de vos espaces d'affaires, adapté à votre horaire d'opération." },
        { title: "Bureaux administratifs", desc: "Environnements de travail propres et sains pour vos employés et vos clients." },
        { title: "Nettoyage post-construction", desc: "Remise à neuf complète après travaux, prête à occuper." },
        { title: "Immeubles et copropriétés", desc: "Entretien des aires communes, halls, corridors, escaliers et ascenseurs." },
        { title: "Cliniques et laboratoires", desc: "Désinfection rigoureuse selon les normes de santé en vigueur." },
        { title: "Hôtellerie et restauration", desc: "Standards de propreté irréprochables pour l'accueil de votre clientèle." },
        { title: "Secteur industriel", desc: "Nettoyage robuste adapté aux environnements de production et d'entrepôt." },
        { title: "Écoles et centres éducatifs", desc: "Milieux sains et sécuritaires pour enfants, élèves et personnel." },
        { title: "Centres sportifs", desc: "Hygiène approfondie des vestiaires, gymnases et aires communes." },
        { title: "Commerces de détail", desc: "Un environnement impeccable qui met vos produits en valeur." },
        { title: "Lavage de vitres", desc: "Vitrines et fenêtres impeccables, à l'intérieur comme à l'extérieur." },
        { title: "Nettoyage en profondeur", desc: "Entretien périodique et intensif pour un renouveau complet des lieux." },
        { title: "Conciergerie", desc: "Présence sur place pour la gestion quotidienne de vos installations." },
        { title: "Entretien de tapis", desc: "Shampouinage et extraction professionnelle pour redonner vie à vos tapis." },
        { title: "Décapage et cirage de planchers", desc: "Restauration et protection durable de vos surfaces." },
      ],
    },
    impact: {
      eyebrow: "L'importance de l'hygiène",
      title: "Un environnement propre, c'est bien plus qu'une question d'apparence",
      subtitle: "C'est essentiel pour la santé de vos employés, leur productivité et la réputation de votre entreprise.",
      items: [
        { title: "Santé et sécurité", desc: "Réduit la propagation des germes, bactéries et virus, pour un environnement plus sécuritaire." },
        { title: "Bien-être des employés", desc: "Un environnement propre améliore le moral, réduit l'absentéisme et le bien-être général." },
        { title: "Image de l'entreprise", desc: "Un bureau impeccable crée une impression positive auprès de vos clients, visiteurs et partenaires." },
        { title: "Productivité accrue", desc: "Des espaces propres et organisés favorisent la concentration et l'efficacité de vos équipes." },
      ],
    },
    deepClean: {
      eyebrow: "Service en vedette",
      title: "Nettoyage en profondeur de bureaux",
      subtitle:
        "Nos services de nettoyage en profondeur vont au-delà de l'entretien régulier pour éliminer la saleté, la crasse et les bactéries jusque dans les moindres recoins de votre bureau, pour un espace hygiénique et revitalisé.",
      checklist: [
        "Désinfection des zones à contact fréquent",
        "Désinfection en profondeur de toutes les surfaces",
        "Dépoussiérage et élimination des allergènes",
        "Élimination des odeurs et fraîcheur de l'air",
      ],
      cta: "Demander une soumission",
    },
    gallery: {
      eyebrow: "Notre travail",
      title: "Le niveau de propreté que nous visons",
      subtitle: "Des espaces impeccables, à la hauteur des standards que nous appliquons chez vous.",
      credit: "Photos à titre indicatif, illustrant le standard visé — à remplacer par vos propres photos.",
      images: [
        { alt: "Corridor lumineux d'un établissement de santé, impeccable", caption: "Cliniques et établissements de santé" },
        { alt: "Membre de notre équipe désinfectant un corridor clinique", caption: "Notre équipe en action — désinfection" },
        { alt: "Espace de bureau moderne aux larges baies vitrées", caption: "Bureaux et espaces de travail" },
        { alt: "Membre de notre équipe désinfectant un poste de travail de bureau", caption: "Notre équipe en action — bureaux" },
        { alt: "Aire commune minimaliste et immaculée", caption: "Aires communes" },
        { alt: "Accueil haut de gamme, entretien irréprochable", caption: "Hôtellerie et espaces de prestige" },
      ],
    },
    why: {
      eyebrow: "Pourquoi nous choisir",
      title: "La qualité et la sécurité, à chaque visite",
      items: [
        { title: "Personnel formé et supervisé", desc: "Une équipe qualifiée, encadrée et évaluée en continu." },
        { title: "Produits écologiques", desc: "Des produits désinfectants respectueux de l'environnement et de la santé." },
        { title: "Protocoles d'hygiène stricts", desc: "Des normes rigoureuses appliquées avec constance." },
        { title: "Présence discrète et respectueuse", desc: "Un service qui s'intègre à votre réalité, sans perturber vos opérations." },
        { title: "Horaires flexibles", desc: "Jour, soir, nuit ou fin de semaine — selon vos besoins." },
        { title: "Contrôle de qualité constant", desc: "Des inspections régulières pour garantir un résultat irréprochable." },
        { title: "Entreprise professionnelle et assurée", desc: "Une tranquillité d'esprit totale pour vous et vos assurances." },
      ],
    },
    promotions: {
      eyebrow: "Offre de bienvenue",
      title: "Nouveaux clients : profitez de nos avantages de bienvenue",
      subtitle: "Vous recherchez un service de nettoyage d'entretien pour votre entreprise, votre commerce ou vos espaces professionnels?",
      perks: [
        {
          title: "6 premiers mois sans contrat",
          desc: "Aucun engagement à long terme pour vous permettre de découvrir la qualité de notre service en toute tranquillité.",
        },
        {
          title: "20 % de rabais sur les travaux supplémentaires",
          desc: "Les clients bénéficiant d'un service de nettoyage d'entretien régulier profitent de 20 % de rabais sur les services supplémentaires, notamment :",
        },
      ],
      extraServices: [
        "Lavage de vitres",
        "Nettoyage de tapis et moquettes",
        "Grand ménage",
        "Décapage et cirage des planchers",
        "Nettoyage en profondeur",
        "Nettoyage des meubles et surfaces",
        "Nettoyage en profondeur des salles de bain",
        "Nettoyage en profondeur des espaces communs",
        "Nettoyage saisonnier",
      ],
      conditions:
        "Valide pour les nouveaux clients qui souscrivent à un service de nettoyage d'entretien régulier, que ce soit quotidiennement, plusieurs fois par semaine ou une fois par semaine.",
      cta: "Profiter de l'offre",
    },
    careers: {
      meta: { title: "A Plus Entretien | Carrières" },
      eyebrow: "Carrières",
      title: "Demandes d'emploi",
      intro: "Vous souhaitez joindre notre équipe?",
      instructions:
        "Toutes les demandes d'emploi doivent être envoyées directement par courriel. Veuillez joindre votre CV à votre courriel afin que nous puissions étudier votre candidature.",
      emailLabel: "Courriel",
      email: "aplusentretien@gmail.com",
      note: "Les candidatures envoyées autrement ne seront pas considérées.",
      cta: "Envoyer mon CV par courriel",
      back: "Retour au site",
    },
    cta: {
      title: "Prêt pour un environnement impeccable ?",
      subtitle: "Obtenez une soumission gratuite et sans engagement, adaptée à vos besoins.",
      button: "Demander ma soumission gratuite",
    },
    contactForm: {
      title: "Demandez votre soumission gratuite",
      subtitle: "Remplissez le formulaire ci-dessous, notre équipe vous répondra rapidement.",
      name: "Nom complet",
      company: "Entreprise (optionnel)",
      email: "Courriel",
      phone: "Téléphone",
      service: "Type de service",
      servicePlaceholder: "Sélectionnez un service",
      message: "Détails de votre projet",
      submit: "Envoyer ma demande",
      namePlaceholder: "Votre nom",
      companyPlaceholder: "Nom de votre entreprise",
      emailPlaceholder: "vous@exemple.com",
      phonePlaceholder: "(514) 000-0000",
      messagePlaceholder: "Décrivez votre espace, sa superficie et la fréquence souhaitée...",
      success: "Merci ! Votre demande a bien été envoyée. Nous vous contacterons sous peu.",
    },
    contact: {
      eyebrow: "Contact",
      title: "Parlons de votre projet",
      phone: "514-562-9969",
      email: "aplusentretien@gmail.com",
      location: "Montréal, Québec",
      locationDesc: "Desservant le Grand Montréal et les environs",
      hoursTitle: "Disponibilité",
      hours: "Horaires flexibles, 7 jours sur 7",
    },
    footer: {
      tagline: "Service d'entretien ménager professionnel — Montréal.",
      rights: "Tous droits réservés.",
      quickLinks: "Liens rapides",
      servicesTitle: "Services",
      contactTitle: "Coordonnées",
    },
  },

  en: {
    meta: {
      title: "A Plus Entretien | Professional Cleaning Services in Montreal",
    },
    nav: {
      home: "Home",
      about: "About",
      services: "Services",
      why: "Why Us",
      promotions: "Promotions",
      contact: "Contact",
      careers: "Careers",
      cta: "Free Quote",
    },
    hero: {
      eyebrow: "Commercial Cleaning · Montreal",
      title: "A+ cleaning service, without compromise.",
      subtitle:
        "Cleanliness and customer satisfaction are our priority. A Montreal family-owned, professional and insured business, serving businesses, institutions and industries.",
      ctaPrimary: "Request a Quote",
      ctaSecondary: "Explore Our Services",
      badge: { title: "Trained & insured team", desc: "Vetted, uniformed, professional" },
      stats: [
        { value: "15+", label: "years of experience" },
        { value: "100%", label: "insured company" },
        { value: "24/7", label: "flexible scheduling" },
      ],
    },
    trustBar: [
      "Insured company",
      "Trained & supervised staff",
      "Eco-friendly products",
      "Strict hygiene protocols",
    ],
    about: {
      eyebrow: "About Us",
      title: "A serious, stable family business",
      paragraphs: [
        "A Plus Entretien is a Montreal-based company specializing in commercial, industrial, and institutional cleaning. Born from a family story, our company is built on integrity, honesty, and hard work.",
        "We treat our staff like family — trained, supervised, and proud of their work — because a respected team delivers consistent, reliable service. This culture is what allows us to keep your facilities at the highest standards of cleanliness, day after day.",
      ],
      highlights: [
        { title: "Reliability", desc: "Consistent service you can count on, week after week." },
        { title: "Rigor", desc: "Precise protocols and quality control on every visit." },
        { title: "Trust", desc: "Vetted staff who are discreet and respectful of your space and schedule." },
      ],
    },
    services: {
      eyebrow: "Our Services",
      title: "Cleaning solutions for every environment",
      subtitle:
        "From offices to factories, clinics to retail stores — expertise tailored to every sector.",
      items: [
        { title: "Commercial Cleaning", desc: "Regular upkeep of your business spaces, tailored to your operating hours." },
        { title: "Administrative Offices", desc: "Clean, healthy work environments for your staff and clients." },
        { title: "Post-Construction Cleaning", desc: "Complete post-renovation cleanup, ready for occupancy." },
        { title: "Buildings & Condos", desc: "Upkeep of common areas, lobbies, hallways, stairs and elevators." },
        { title: "Clinics & Laboratories", desc: "Rigorous disinfection following current health standards." },
        { title: "Hospitality & Restaurants", desc: "Impeccable cleanliness standards for welcoming your clientele." },
        { title: "Industrial Sector", desc: "Robust cleaning suited to production floors and warehouses." },
        { title: "Schools & Daycares", desc: "Safe, healthy environments for children, students and staff." },
        { title: "Sports Centers", desc: "Thorough hygiene for locker rooms, gyms and common areas." },
        { title: "Retail Stores", desc: "An immaculate environment that showcases your products." },
        { title: "Window Cleaning", desc: "Spotless storefronts and windows, inside and out." },
        { title: "Deep Cleaning", desc: "Periodic, intensive maintenance for a full refresh of your space." },
        { title: "Concierge Service", desc: "On-site presence for day-to-day facility management." },
        { title: "Carpet Cleaning", desc: "Professional shampooing and extraction to restore your carpets." },
        { title: "Floor Stripping & Waxing", desc: "Long-lasting restoration and protection of your surfaces." },
      ],
    },
    impact: {
      eyebrow: "The Importance of Workplace Hygiene",
      title: "A clean workplace is more than just appearance",
      subtitle: "It's essential for employee health, productivity, and your business reputation.",
      items: [
        { title: "Health & Safety", desc: "Reduces the spread of germs, bacteria & viruses, ensuring a safer environment." },
        { title: "Employee Well-Being", desc: "A clean environment boosts morale, reduces sick leave and improves overall well-being." },
        { title: "Business Image", desc: "A spotless office creates a positive impression on clients, visitors and partners." },
        { title: "Higher Productivity", desc: "Clean and organized workspaces lead to better focus and increased efficiency." },
      ],
    },
    deepClean: {
      eyebrow: "Featured Service",
      title: "Office Deep Cleaning",
      subtitle:
        "Our deep cleaning services go beyond regular upkeep to remove dirt, grime and bacteria from every corner of your office, ensuring a hygienic and refreshed workspace.",
      checklist: [
        "High-touch area disinfection",
        "Deep sanitization of all surfaces",
        "Dusting & allergen removal",
        "Odor elimination & air freshness",
      ],
      cta: "Request a Quote",
    },
    gallery: {
      eyebrow: "Our Work",
      title: "The standard of clean we hold ourselves to",
      subtitle: "Immaculate spaces, reflecting the standards we apply on your site.",
      credit: "Placeholder photos illustrating the target standard — swap in your own photos.",
      images: [
        { alt: "Bright, spotless corridor in a healthcare facility", caption: "Clinics & Healthcare Facilities" },
        { alt: "Our team member disinfecting a clinical corridor", caption: "Our Team in Action — Disinfection" },
        { alt: "Modern office space with expansive glass windows", caption: "Offices & Workspaces" },
        { alt: "Our team member sanitizing an office workstation", caption: "Our Team in Action — Offices" },
        { alt: "Minimalist, immaculate common area", caption: "Common Areas" },
        { alt: "Upscale reception area, flawlessly maintained", caption: "Hospitality & Premium Spaces" },
      ],
    },
    why: {
      eyebrow: "Why Choose Us",
      title: "Quality and safety, on every visit",
      items: [
        { title: "Trained & supervised staff", desc: "A qualified team, supervised and continuously evaluated." },
        { title: "Eco-friendly products", desc: "Disinfecting products that respect the environment and health." },
        { title: "Strict hygiene protocols", desc: "Rigorous standards applied consistently." },
        { title: "Discreet, respectful presence", desc: "A service that fits your reality, without disrupting your operations." },
        { title: "Flexible scheduling", desc: "Day, evening, night, or weekend — based on your needs." },
        { title: "Constant quality control", desc: "Regular inspections to guarantee flawless results." },
        { title: "Professional & insured company", desc: "Total peace of mind for you and your insurers." },
      ],
    },
    promotions: {
      eyebrow: "Welcome Offer",
      title: "New Clients: Enjoy Our Welcome Benefits",
      subtitle: "Looking for a cleaning maintenance service for your business, store, or professional spaces?",
      perks: [
        {
          title: "First 6 months, no contract",
          desc: "No long-term commitment, so you can discover the quality of our service with total peace of mind.",
        },
        {
          title: "20% off additional work",
          desc: "Clients with a regular cleaning maintenance service enjoy 20% off additional services, including:",
        },
      ],
      extraServices: [
        "Window cleaning",
        "Carpet & rug cleaning",
        "Deep spring cleaning",
        "Floor stripping & waxing",
        "Deep cleaning",
        "Furniture & surface cleaning",
        "Deep bathroom cleaning",
        "Deep cleaning of common areas",
        "Seasonal cleaning",
      ],
      conditions:
        "Valid for new clients who subscribe to a regular cleaning maintenance service — daily, several times a week, or once a week.",
      cta: "Take Advantage of This Offer",
    },
    careers: {
      meta: { title: "A Plus Entretien | Careers" },
      eyebrow: "Careers",
      title: "Job Applications",
      intro: "Want to join our team?",
      instructions:
        "All job applications must be sent directly by email. Please attach your resume to your email so we can review your application.",
      emailLabel: "Email",
      email: "aplusentretien@gmail.com",
      note: "Applications submitted any other way will not be considered.",
      cta: "Email My Resume",
      back: "Back to site",
    },
    cta: {
      title: "Ready for a spotless environment?",
      subtitle: "Get a free, no-obligation quote tailored to your needs.",
      button: "Get My Free Quote",
    },
    contactForm: {
      title: "Request Your Free Quote",
      subtitle: "Fill out the form below and our team will get back to you promptly.",
      name: "Full Name",
      company: "Company (optional)",
      email: "Email",
      phone: "Phone",
      service: "Service Type",
      servicePlaceholder: "Select a service",
      message: "Project Details",
      submit: "Send My Request",
      namePlaceholder: "Your name",
      companyPlaceholder: "Your company name",
      emailPlaceholder: "you@example.com",
      phonePlaceholder: "(514) 000-0000",
      messagePlaceholder: "Describe your space, its size, and the desired frequency...",
      success: "Thank you! Your request has been sent. We'll be in touch shortly.",
    },
    contact: {
      eyebrow: "Contact",
      title: "Let's talk about your project",
      phone: "514-562-9969",
      email: "aplusentretien@gmail.com",
      location: "Montreal, Quebec",
      locationDesc: "Serving Greater Montreal and surrounding areas",
      hoursTitle: "Availability",
      hours: "Flexible scheduling, 7 days a week",
    },
    footer: {
      tagline: "Professional cleaning services — Montreal.",
      rights: "All rights reserved.",
      quickLinks: "Quick Links",
      servicesTitle: "Services",
      contactTitle: "Contact",
    },
  },
}
